import React, { useCallback, useState } from 'react';
import { Alert, Image, Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Text } from '../src/components/TranslatedText';
import { router, useFocusEffect, useLocalSearchParams } from '../src/navigation';
import { AppShell } from '../src/components/AppShell';
import { Button } from '../src/components/Button';
import { Card } from '../src/components/Card';
import { Input } from '../src/components/Input';
import { colors, spacing } from '../src/constants/theme';
import { pickAndSaveClientPhoto, shareFile } from '../src/storage/fileStore';
import { localStore } from '../src/storage/localStore';
import { Client } from '../src/types';

function initial(name: string) { return (name || '?').trim().slice(0, 1).toUpperCase(); }

export default function ClientProfileScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [client, setClient] = useState<Client | null>(null);
  const [draft, setDraft] = useState<Client | null>(null);
  const [edit, setEdit] = useState(false);

  const load = useCallback(() => { if (id) localStore.getClient(id).then(c => { setClient(c); setDraft(c); }); }, [id]);
  useFocusEffect(load);

  async function save() { if (!draft) return; await localStore.upsertClient(draft); setClient(draft); setEdit(false); Alert.alert('Сохранено', 'Данные клиента обновлены.'); }
  async function pickClientPhoto() { const uri = await pickAndSaveClientPhoto(); if (uri) setDraft(p => p ? { ...p, photoUri: uri } : p); }
  function confirmDelete() { if (!client) return; Alert.alert('Удалить клиента?', 'Будут удалены данные, оплаты и отчёты только этого клиента. Шаблоны не удаляются.', [{ text: 'Отмена', style: 'cancel' }, { text: 'Да, удалить', style: 'destructive', onPress: async () => { await localStore.deleteClient(client.id); router.replace('/clients' as never); } }]); }
  async function sendActivePlan() { const active = client?.assignedPlanHistory?.find(p => p.status === 'active'); if (!active?.fileUri) return Alert.alert('Файл не выбран', 'У клиента нет активного файла программы.'); await shareFile(active.fileUri, 'Отправить программу клиенту'); }
  async function archiveAssigned(programId: string) { if (!client) return; const next = { ...client, assignedPlanHistory: (client.assignedPlanHistory || []).map(p => p.id === programId ? { ...p, status: 'archived' as const } : p) }; await localStore.upsertClient(next); setClient(next); }

  if (!client) return <AppShell title="Клиент" active="clients"><View style={styles.center}><Text style={styles.muted}>Клиент не найден</Text></View></AppShell>;

  return <AppShell title="Карточка клиента" active="clients"><ScrollView contentContainerStyle={styles.content}>
    <Card style={styles.profileCard}><View style={styles.profileRow}>{client.photoUri ? <Image source={{ uri: client.photoUri }} style={styles.avatar} /> : <View style={styles.avatarPlaceholder}><Text style={styles.initial}>{initial(client.name)}</Text></View>}<View style={styles.info}><Text style={styles.name}>{client.name}</Text><Text style={styles.status}>● {client.status === 'active' ? 'Активен' : 'Не активен'}</Text><Text style={styles.line}>🎯 {client.goal || 'Цель не указана'}</Text><Text style={styles.line}>💰 {client.amount || 'Тариф не указан'}</Text><Text style={styles.line}>🗓️ до: {client.endsAt || '—'}</Text></View></View></Card>
    <Card style={styles.actions}><Button title="✏ Изменить клиента" onPress={() => setEdit(true)} /><Button title="📋 Назначить программу" onPress={() => router.replace('/assign' as never)} variant="secondary" /><Button title="📤 Отправить активную программу" onPress={sendActivePlan} variant="outline" /><Button title="🗑 Удалить клиента" onPress={confirmDelete} variant="danger" /></Card>
    <Card style={styles.history}><Text style={styles.sectionTitle}>Назначенные программы</Text>{(client.assignedPlanHistory || []).length === 0 ? <Text style={styles.muted}>История назначений пуста.</Text> : (client.assignedPlanHistory || []).map(p => <View key={p.id} style={styles.programRow}><View style={{ flex: 1 }}><Text style={styles.programTitle}>{p.title}</Text><Text style={styles.programSub}>{p.duration || '—'} • {new Date(p.assignedAt).toLocaleDateString('ru-RU')}</Text><Text style={[styles.programStatus, p.status === 'active' ? { color: colors.success } : { color: colors.muted }]}>{p.status === 'active' ? 'Активна' : 'Архив'}</Text></View><View style={styles.programActions}><Pressable onPress={() => p.fileUri ? shareFile(p.fileUri, 'Просмотр/отправка файла') : Alert.alert('Нет файла')}><Text style={styles.actionText}>👁 Просмотр</Text></Pressable><Pressable onPress={() => router.replace('/assign' as never)}><Text style={styles.actionText}>✏ Изменить</Text></Pressable><Pressable onPress={() => archiveAssigned(p.id)}><Text style={styles.deleteText}>🗑 Удалить</Text></Pressable></View></View>)}</Card>
    <Modal visible={edit} animationType="slide" onRequestClose={() => setEdit(false)}><View style={styles.modalRoot}><ScrollView contentContainerStyle={styles.modalContent}><Text style={styles.modalTitle}>Изменить клиента</Text>{draft && <><View style={styles.editPhotoRow}>{draft.photoUri ? <Image source={{ uri: draft.photoUri }} style={styles.editAvatar} /> : <View style={styles.editAvatarPlaceholder}><Text style={styles.editInitial}>{initial(draft.name)}</Text></View>}<Pressable onPress={pickClientPhoto} style={styles.photoButton}><Text style={styles.photoButtonText}>📷 Изменить фото клиента</Text></Pressable></View><Input placeholder="ФИО" value={draft.name} onChangeText={v => setDraft(p => p ? { ...p, name: v } : p)} /><Input placeholder="Телефон" value={draft.phone} onChangeText={v => setDraft(p => p ? { ...p, phone: v } : p)} /><Input placeholder="Цель" value={draft.goal} onChangeText={v => setDraft(p => p ? { ...p, goal: v } : p)} /><Input placeholder="Сумма / тариф" value={draft.amount} onChangeText={v => setDraft(p => p ? { ...p, amount: v } : p)} /><Input placeholder="Оплачено до" value={draft.endsAt} onChangeText={v => setDraft(p => p ? { ...p, endsAt: v } : p)} /><Input placeholder="Комментарий" value={draft.comment} onChangeText={v => setDraft(p => p ? { ...p, comment: v } : p)} multiline /><Button title="💾 Сохранить изменения" onPress={save} /><Button title="🗑 Удалить клиента" onPress={confirmDelete} variant="danger" /><Button title="← Назад" onPress={() => setEdit(false)} variant="secondary" /></>}</ScrollView></View></Modal>
  </ScrollView></AppShell>;
}

const styles = StyleSheet.create({ content: { padding: spacing.md, paddingBottom: 120 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, profileCard: { padding: 14, borderRadius: 22 }, profileRow: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 88, height: 88, borderRadius: 44, marginRight: 14 }, avatarPlaceholder: { width: 88, height: 88, borderRadius: 44, marginRight: 14, backgroundColor: colors.client, alignItems: 'center', justifyContent: 'center' }, initial: { fontSize: 34, color: '#FFF', fontWeight: '900' }, info: { flex: 1 }, name: { fontSize: 23, color: colors.text, fontWeight: '900' }, status: { color: colors.success, fontWeight: '900', fontSize: 15, marginTop: 4 }, line: { color: colors.muted, fontWeight: '800', fontSize: 14, marginTop: 3 }, actions: { padding: 12, marginTop: 10, borderRadius: 22 }, history: { padding: 12, marginTop: 10, borderRadius: 22 }, sectionTitle: { color: colors.gold, fontSize: 20, fontWeight: '900', marginBottom: 10 }, muted: { color: colors.muted, fontSize: 14, fontWeight: '700' }, programRow: { borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: 10, flexDirection: 'row', gap: 10 }, programTitle: { color: colors.text, fontWeight: '900', fontSize: 16 }, programSub: { color: colors.muted, fontSize: 13, marginTop: 3 }, programStatus: { fontSize: 13, fontWeight: '900', marginTop: 3 }, programActions: { width: 108, gap: 7 }, actionText: { color: colors.text, fontWeight: '800', fontSize: 12 }, deleteText: { color: colors.red, fontWeight: '900', fontSize: 12 }, modalRoot: { flex: 1, backgroundColor: colors.background }, modalContent: { padding: spacing.md, paddingTop: 48, paddingBottom: 40 }, modalTitle: { color: colors.gold, fontWeight: '900', fontSize: 25, marginBottom: 12 }, editPhotoRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 }, editAvatar: { width: 72, height: 72, borderRadius: 36 }, editAvatarPlaceholder: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.client, alignItems: 'center', justifyContent: 'center' }, editInitial: { fontSize: 27, color: '#FFF', fontWeight: '900' }, photoButton: { flex: 1, height: 52, borderRadius: 16, borderWidth: 1, borderColor: colors.gold, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card }, photoButtonText: { color: colors.gold, fontSize: 15, fontWeight: '900' } });
